// Professional Book Library Dataset
// 100 curated books appropriate for educational/workplace settings
// Array-based genres allow books to span multiple categories

export const bookData = [
  // Business & Leadership
  {
    id: 1,
    title: 'Good to Great',
    author: 'Jim Collins',
    rating: 4.3,
    genres: ['Business', 'Leadership'],
    pages: 320,
    price: 28.99,
    publishYear: 2001,
  },
  {
    id: 2,
    title: 'The 7 Habits of Highly Effective People',
    author: 'Stephen R. Covey',
    rating: 4.1,
    genres: ['Business', 'Personal Development'],
    pages: 381,
    price: 16.99,
    publishYear: 1989,
  },
  {
    id: 3,
    title: 'Drive: The Surprising Truth About What Motivates Us',
    author: 'Daniel H. Pink',
    rating: 4.2,
    genres: ['Business', 'Psychology'],
    pages: 272,
    price: 17.99,
    publishYear: 2009,
  },
  {
    id: 4,
    title: 'The Lean Startup',
    author: 'Eric Ries',
    rating: 4.1,
    genres: ['Business', 'Technology'],
    pages: 336,
    price: 19.99,
    publishYear: 2011,
  },
  {
    id: 5,
    title: 'Start With Why',
    author: 'Simon Sinek',
    rating: 4.0,
    genres: ['Business', 'Leadership'],
    pages: 256,
    price: 18.99,
    publishYear: 2009,
  },
  {
    id: 6,
    title: 'Dare to Lead',
    author: 'Brené Brown',
    rating: 4.4,
    genres: ['Leadership', 'Personal Development'],
    pages: 320,
    price: 24.99,
    publishYear: 2018,
  },
  {
    id: 7,
    title: 'The Effective Executive',
    author: 'Peter F. Drucker',
    rating: 4.2,
    genres: ['Business', 'Management'],
    pages: 206,
    price: 15.99,
    publishYear: 1966,
  },
  {
    id: 8,
    title: 'Blue Ocean Strategy',
    author: 'W. Chan Kim & Renée Mauborgne',
    rating: 3.9,
    genres: ['Business', 'Strategy'],
    pages: 272,
    price: 22.99,
    publishYear: 2005,
  },
  {
    id: 9,
    title: 'Lean In',
    author: 'Sheryl Sandberg',
    rating: 4.0,
    genres: ['Business', 'Leadership'],
    pages: 240,
    price: 16.99,
    publishYear: 2013,
  },
  {
    id: 10,
    title: 'How to Win Friends and Influence People',
    author: 'Dale Carnegie',
    rating: 4.3,
    genres: ['Business', 'Communication'],
    pages: 291,
    price: 14.99,
    publishYear: 1936,
  },

  // Technology & Programming
  {
    id: 11,
    title: 'Clean Code',
    author: 'Robert C. Martin',
    rating: 4.4,
    genres: ['Technology', 'Programming'],
    pages: 464,
    price: 42.99,
    publishYear: 2008,
  },
  {
    id: 12,
    title: 'The Pragmatic Programmer',
    author: 'David Thomas & Andrew Hunt',
    rating: 4.3,
    genres: ['Technology', 'Programming'],
    pages: 352,
    price: 39.99,
    publishYear: 1999,
  },
  {
    id: 13,
    title: 'Design Patterns',
    author: 'Erich Gamma',
    rating: 4.1,
    genres: ['Technology', 'Programming'],
    pages: 395,
    price: 54.99,
    publishYear: 1994,
  },
  {
    id: 14,
    title: 'JavaScript: The Good Parts',
    author: 'Douglas Crockford',
    rating: 4.0,
    genres: ['Technology', 'Programming'],
    pages: 176,
    price: 34.99,
    publishYear: 2008,
  },
  {
    id: 15,
    title: 'Code Complete',
    author: 'Steve McConnell',
    rating: 4.5,
    genres: ['Technology', 'Programming'],
    pages: 914,
    price: 44.99,
    publishYear: 2004,
  },
  {
    id: 16,
    title: 'The Mythical Man-Month',
    author: 'Frederick P. Brooks Jr.',
    rating: 4.0,
    genres: ['Technology', 'Management'],
    pages: 322,
    price: 29.99,
    publishYear: 1975,
  },
  {
    id: 17,
    title: "Don't Make Me Think",
    author: 'Steve Krug',
    rating: 4.2,
    genres: ['Technology', 'Design'],
    pages: 216,
    price: 32.99,
    publishYear: 2000,
  },
  {
    id: 18,
    title: 'The Phoenix Project',
    author: 'Gene Kim',
    rating: 4.3,
    genres: ['Technology', 'Business'],
    pages: 345,
    price: 26.99,
    publishYear: 2013,
  },
  {
    id: 19,
    title: 'Refactoring',
    author: 'Martin Fowler',
    rating: 4.1,
    genres: ['Technology', 'Programming'],
    pages: 448,
    price: 49.99,
    publishYear: 1999,
  },
  {
    id: 20,
    title: 'The C Programming Language',
    author: 'Brian W. Kernighan & Dennis M. Ritchie',
    rating: 4.4,
    genres: ['Technology', 'Programming'],
    pages: 274,
    price: 38.99,
    publishYear: 1978,
  },

  // Science & Innovation
  {
    id: 21,
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    rating: 4.1,
    genres: ['Science', 'Psychology'],
    pages: 499,
    price: 17.99,
    publishYear: 2011,
  },
  {
    id: 22,
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    rating: 4.4,
    genres: ['Science', 'History'],
    pages: 443,
    price: 21.99,
    publishYear: 2011,
  },
  {
    id: 23,
    title: 'The Tipping Point',
    author: 'Malcolm Gladwell',
    rating: 3.9,
    genres: ['Science', 'Psychology'],
    pages: 301,
    price: 16.99,
    publishYear: 2000,
  },
  {
    id: 24,
    title: 'Freakonomics',
    author: 'Steven D. Levitt & Stephen J. Dubner',
    rating: 3.8,
    genres: ['Science', 'Economics'],
    pages: 320,
    price: 16.99,
    publishYear: 2005,
  },
  {
    id: 25,
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    rating: 4.2,
    genres: ['Science', 'Physics'],
    pages: 256,
    price: 18.99,
    publishYear: 1988,
  },
  {
    id: 26,
    title: 'Silent Spring',
    author: 'Rachel Carson',
    rating: 4.1,
    genres: ['Science', 'Environment'],
    pages: 378,
    price: 15.99,
    publishYear: 1962,
  },
  {
    id: 27,
    title: 'The Selfish Gene',
    author: 'Richard Dawkins',
    rating: 4.3,
    genres: ['Science', 'Biology'],
    pages: 360,
    price: 17.99,
    publishYear: 1976,
  },
  {
    id: 28,
    title: 'Cosmos',
    author: 'Carl Sagan',
    rating: 4.4,
    genres: ['Science', 'Astronomy'],
    pages: 384,
    price: 18.99,
    publishYear: 1980,
  },
  {
    id: 29,
    title: 'Guns, Germs, and Steel',
    author: 'Jared Diamond',
    rating: 4.0,
    genres: ['Science', 'History'],
    pages: 480,
    price: 17.99,
    publishYear: 1997,
  },
  {
    id: 30,
    title: 'The Structure of Scientific Revolutions',
    author: 'Thomas S. Kuhn',
    rating: 4.0,
    genres: ['Science', 'Philosophy'],
    pages: 264,
    price: 16.99,
    publishYear: 1962,
  },

  // Literature & Classics
  {
    id: 31,
    title: '1984',
    author: 'George Orwell',
    rating: 4.4,
    genres: ['Literature', 'Political'],
    pages: 328,
    price: 13.99,
    publishYear: 1949,
  },
  {
    id: 32,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    rating: 4.3,
    genres: ['Literature', 'Social Issues'],
    pages: 376,
    price: 14.99,
    publishYear: 1960,
  },
  {
    id: 33,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    rating: 4.2,
    genres: ['Literature', 'Romance'],
    pages: 432,
    price: 12.99,
    publishYear: 1813,
  },
  {
    id: 34,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    rating: 3.9,
    genres: ['Literature', 'American'],
    pages: 180,
    price: 13.99,
    publishYear: 1925,
  },
  {
    id: 35,
    title: 'Animal Farm',
    author: 'George Orwell',
    rating: 4.1,
    genres: ['Literature', 'Political'],
    pages: 112,
    price: 11.99,
    publishYear: 1945,
  },
  {
    id: 36,
    title: 'Beloved',
    author: 'Toni Morrison',
    rating: 4.0,
    genres: ['Literature', 'American'],
    pages: 324,
    price: 15.99,
    publishYear: 1987,
  },
  {
    id: 37,
    title: 'The Grapes of Wrath',
    author: 'John Steinbeck',
    rating: 4.1,
    genres: ['Literature', 'American'],
    pages: 464,
    price: 16.99,
    publishYear: 1939,
  },
  {
    id: 38,
    title: 'Mrs. Dalloway',
    author: 'Virginia Woolf',
    rating: 3.8,
    genres: ['Literature', 'Modernist'],
    pages: 194,
    price: 14.99,
    publishYear: 1925,
  },
  {
    id: 39,
    title: 'A Tale of Two Cities',
    author: 'Charles Dickens',
    rating: 3.9,
    genres: ['Literature', 'Historical'],
    pages: 489,
    price: 12.99,
    publishYear: 1859,
  },
  {
    id: 40,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    rating: 3.8,
    genres: ['Literature', 'Coming-of-Age'],
    pages: 277,
    price: 13.99,
    publishYear: 1951,
  },

  // Personal Development
  {
    id: 41,
    title: 'Mindset: The New Psychology of Success',
    author: 'Carol S. Dweck',
    rating: 4.1,
    genres: ['Personal Development', 'Psychology'],
    pages: 320,
    price: 17.99,
    publishYear: 2006,
  },
  {
    id: 42,
    title: 'Atomic Habits',
    author: 'James Clear',
    rating: 4.6,
    genres: ['Personal Development', 'Self-Help'],
    pages: 320,
    price: 18.99,
    publishYear: 2018,
  },
  {
    id: 43,
    title: 'Deep Work',
    author: 'Cal Newport',
    rating: 4.2,
    genres: ['Personal Development', 'Productivity'],
    pages: 296,
    price: 16.99,
    publishYear: 2016,
  },
  {
    id: 44,
    title: 'Grit: The Power of Passion and Perseverance',
    author: 'Angela Duckworth',
    rating: 4.0,
    genres: ['Personal Development', 'Psychology'],
    pages: 352,
    price: 17.99,
    publishYear: 2016,
  },
  {
    id: 45,
    title: "Man's Search for Meaning",
    author: 'Viktor E. Frankl',
    rating: 4.4,
    genres: ['Personal Development', 'Philosophy'],
    pages: 165,
    price: 14.99,
    publishYear: 1946,
  },
  {
    id: 46,
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    rating: 4.1,
    genres: ['Personal Development', 'Spirituality'],
    pages: 236,
    price: 16.99,
    publishYear: 1997,
  },
  {
    id: 47,
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    rating: 4.0,
    genres: ['Personal Development', 'Business'],
    pages: 238,
    price: 12.99,
    publishYear: 1937,
  },
  {
    id: 48,
    title: 'Emotional Intelligence',
    author: 'Daniel Goleman',
    rating: 4.0,
    genres: ['Personal Development', 'Psychology'],
    pages: 384,
    price: 17.99,
    publishYear: 1995,
  },
  {
    id: 49,
    title: 'Getting Things Done',
    author: 'David Allen',
    rating: 3.9,
    genres: ['Personal Development', 'Productivity'],
    pages: 352,
    price: 16.99,
    publishYear: 2001,
  },
  {
    id: 50,
    title: 'Eat That Frog!',
    author: 'Brian Tracy',
    rating: 4.0,
    genres: ['Personal Development', 'Productivity'],
    pages: 144,
    price: 13.99,
    publishYear: 2001,
  },
  // Additional Professional Books - Technology & Science
  {
    id: 51,
    title: 'Clean Architecture',
    author: 'Robert C. Martin',
    rating: 4.4,
    genres: ['Programming', 'Software Engineering'],
    pages: 432,
    price: 39.99,
    publishYear: 2017,
  },

  {
    id: 52,
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen',
    rating: 4.2,
    genres: ['Computer Science', 'Programming'],
    pages: 1312,
    price: 89.99,
    publishYear: 2009,
  },

  {
    id: 53,
    title: "You Don't Know JS",
    author: 'Kyle Simpson',
    rating: 4.6,
    genres: ['Programming', 'JavaScript'],
    pages: 278,
    price: 24.99,
    publishYear: 2014,
  },

  {
    id: 54,
    title: 'System Design Interview',
    author: 'Alex Xu',
    rating: 4.4,
    genres: ['Technology', 'Career'],
    pages: 322,
    price: 35.99,
    publishYear: 2020,
  },

  {
    id: 55,
    title: 'Cracking the Coding Interview',
    author: 'Gayle Laakmann McDowell',
    rating: 4.2,
    genres: ['Programming', 'Career'],
    pages: 687,
    price: 47.99,
    publishYear: 2015,
  },
  // Psychology & Human Behavior
  {
    id: 56,
    title: 'Influence: The Psychology of Persuasion',
    author: 'Robert B. Cialdini',
    rating: 4.3,
    genres: ['Psychology', 'Communication'],
    pages: 320,
    price: 18.99,
    publishYear: 2006,
  },
  {
    id: 57,
    title: 'The Power of Habit',
    author: 'Charles Duhigg',
    rating: 4.2,
    genres: ['Psychology', 'Personal Development'],
    pages: 371,
    price: 17.99,
    publishYear: 2012,
  },
  {
    id: 58,
    title: 'Nudge',
    author: 'Richard H. Thaler',
    rating: 4.1,
    genres: ['Psychology', 'Economics'],
    pages: 293,
    price: 16.99,
    publishYear: 2008,
  },
  {
    id: 59,
    title: 'The Paradox of Choice',
    author: 'Barry Schwartz',
    rating: 4.0,
    genres: ['Psychology', 'Decision Making'],
    pages: 304,
    price: 16.99,
    publishYear: 2004,
  },

  // Science & Innovation
  {
    id: 60,
    title: "The Innovator's Dilemma",
    author: 'Clayton M. Christensen',
    rating: 4.2,
    genres: ['Business', 'Innovation'],
    pages: 288,
    price: 18.99,
    publishYear: 1997,
  },

  {
    id: 61,
    title: 'The Art of War',
    author: 'Sun Tzu',
    rating: 4.0,
    genres: ['Strategy', 'Philosophy'],
    pages: 273,
    price: 12.99,
    publishYear: 2003,
  },

  {
    id: 62,
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    rating: 4.4,
    genres: ['History', 'Anthropology'],
    pages: 443,
    price: 21.99,
    publishYear: 2014,
  },
  // Data Science & Analytics
  {
    id: 63,
    title: 'Python for Data Analysis',
    author: 'Wes McKinney',
    rating: 4.3,
    genres: ['Data Science', 'Python'],
    pages: 544,
    price: 49.99,
    publishYear: 2017,
  },
  {
    id: 64,
    title: 'Hands-On Machine Learning',
    author: 'Aurélien Géron',
    rating: 4.5,
    genres: ['Machine Learning', 'Data Science'],
    pages: 851,
    price: 59.99,
    publishYear: 2019,
  },
  {
    id: 65,
    title: 'The Signal and the Noise',
    author: 'Nate Silver',
    rating: 4.1,
    genres: ['Statistics', 'Data Science'],
    pages: 534,
    price: 17.99,
    publishYear: 2012,
  },
  {
    id: 66,
    title: 'Storytelling with Data',
    author: 'Cole Nussbaumer Knaflic',
    rating: 4.4,
    genres: ['Data Visualization', 'Communication'],
    pages: 288,
    price: 24.99,
    publishYear: 2015,
  },
  {
    id: 67,
    title: 'The Elements of Statistical Learning',
    author: 'Trevor Hastie',
    rating: 4.2,
    genres: ['Statistics', 'Machine Learning'],
    pages: 745,
    price: 84.99,
    publishYear: 2016,
  },
  // Finance & Economics
  {
    id: 68,
    title: 'The Intelligent Investor',
    author: 'Benjamin Graham',
    rating: 4.3,
    genres: ['Finance', 'Investing'],
    pages: 640,
    price: 22.99,
    publishYear: 2006,
  },
  {
    id: 69,
    title: 'A Random Walk Down Wall Street',
    author: 'Burton G. Malkiel',
    rating: 4.2,
    genres: ['Finance', 'Economics'],
    pages: 448,
    price: 19.99,
    publishYear: 2019,
  },

  {
    id: 70,
    title: 'The Wealth of Nations',
    author: 'Adam Smith',
    rating: 3.9,
    genres: ['Economics', 'Philosophy'],
    pages: 1264,
    price: 14.99,
    publishYear: 2003,
  },
  {
    id: 71,
    title: 'Capital in the Twenty-First Century',
    author: 'Thomas Piketty',
    rating: 4.0,
    genres: ['Economics', 'Politics'],
    pages: 696,
    price: 39.99,
    publishYear: 2014,
  },
  // Communication & Writing
  {
    id: 72,
    title: 'Made to Stick',
    author: 'Chip Heath',
    rating: 4.2,
    genres: ['Communication', 'Marketing'],
    pages: 291,
    price: 16.99,
    publishYear: 2007,
  },
  {
    id: 73,
    title: 'The Elements of Style',
    author: 'William Strunk Jr.',
    rating: 4.1,
    genres: ['Writing', 'Communication'],
    pages: 105,
    price: 9.99,
    publishYear: 1999,
  },
  {
    id: 74,
    title: 'On Writing Well',
    author: 'William Zinsser',
    rating: 4.3,
    genres: ['Writing', 'Communication'],
    pages: 336,
    price: 15.99,
    publishYear: 2006,
  },
  {
    id: 75,
    title: 'Difficult Conversations',
    author: 'Douglas Stone',
    rating: 4.2,
    genres: ['Communication', 'Conflict Resolution'],
    pages: 352,
    price: 17.99,
    publishYear: 2010,
  },
  {
    id: 76,
    title: 'Never Eat Alone',
    author: 'Keith Ferrazzi',
    rating: 4.1,
    genres: ['Networking', 'Career'],
    pages: 308,
    price: 16.99,
    publishYear: 2014,
  },
  // Health & Wellness
  {
    id: 77,
    title: 'The 4-Hour Body',
    author: 'Timothy Ferriss',
    rating: 3.9,
    genres: ['Health', 'Fitness'],
    pages: 571,
    price: 19.99,
    publishYear: 2010,
  },
  {
    id: 78,
    title: 'Why We Sleep',
    author: 'Matthew Walker',
    rating: 4.4,
    genres: ['Health', 'Science'],
    pages: 368,
    price: 17.99,
    publishYear: 2017,
  },
  {
    id: 79,
    title: 'The Blue Zones',
    author: 'Dan Buettner',
    rating: 4.2,
    genres: ['Health', 'Longevity'],
    pages: 304,
    price: 16.99,
    publishYear: 2012,
  },

  {
    id: 80,
    title: 'Flow: The Psychology of Optimal Experience',
    author: 'Mihaly Csikszentmihalyi',
    rating: 4.2,
    genres: ['Psychology', 'Performance'],
    pages: 303,
    price: 16.99,
    publishYear: 2008,
  },
  // Philosophy & Critical Thinking
  {
    id: 81,
    title: 'The Republic',
    author: 'Plato',
    rating: 4.0,
    genres: ['Philosophy', 'Political Science'],
    pages: 514,
    price: 13.99,
    publishYear: 2007,
  },
  {
    id: 82,
    title: 'Meditations',
    author: 'Marcus Aurelius',
    rating: 4.3,
    genres: ['Philosophy', 'Stoicism'],
    pages: 304,
    price: 12.99,
    publishYear: 2006,
  },
  {
    id: 83,
    title: 'The Art of Thinking Clearly',
    author: 'Rolf Dobelli',
    rating: 4.1,
    genres: ['Psychology', 'Decision Making'],
    pages: 384,
    price: 15.99,
    publishYear: 2013,
  },

  {
    id: 84,
    title: 'The Black Swan',
    author: 'Nassim Nicholas Taleb',
    rating: 4.1,
    genres: ['Philosophy', 'Risk Management'],
    pages: 444,
    price: 17.99,
    publishYear: 2010,
  },
  // Project Management & Operations

  {
    id: 85,
    title: 'Scrum: The Art of Doing Twice the Work',
    author: 'Jeff Sutherland',
    rating: 4.2,
    genres: ['Agile', 'Project Management'],
    pages: 248,
    price: 17.99,
    publishYear: 2014,
  },
  {
    id: 86,
    title: 'The DevOps Handbook',
    author: 'Gene Kim',
    rating: 4.3,
    genres: ['DevOps', 'Technology'],
    pages: 480,
    price: 39.99,
    publishYear: 2016,
  },
  {
    id: 87,
    title: 'Measure What Matters',
    author: 'John Doerr',
    rating: 4.2,
    genres: ['Business', 'Goal Setting'],
    pages: 306,
    price: 28.99,
    publishYear: 2018,
  },
  // Additional Unique Books
  {
    id: 88,
    title: 'The Art of Learning',
    author: 'Josh Waitzkin',
    rating: 4.3,
    genres: ['Personal Development', 'Learning'],
    pages: 288,
    price: 16.99,
    publishYear: 2007,
  },
  {
    id: 89,
    title: 'Range: Why Generalists Triumph',
    author: 'David Epstein',
    rating: 4.2,
    genres: ['Psychology', 'Career'],
    pages: 352,
    price: 18.99,
    publishYear: 2019,
  },
  {
    id: 90,
    title: 'The Design of Everyday Things',
    author: 'Don Norman',
    rating: 4.1,
    genres: ['Design', 'Psychology'],
    pages: 368,
    price: 17.99,
    publishYear: 2013,
  },
  {
    id: 91,
    title: 'Principles: Life and Work',
    author: 'Ray Dalio',
    rating: 4.0,
    genres: ['Business', 'Finance'],
    pages: 592,
    price: 32.99,
    publishYear: 2017,
  },
  {
    id: 92,
    title: 'The Checklist Manifesto',
    author: 'Atul Gawande',
    rating: 4.2,
    genres: ['Productivity', 'Healthcare'],
    pages: 224,
    price: 15.99,
    publishYear: 2009,
  },
  {
    id: 93,
    title: 'Antifragile',
    author: 'Nassim Nicholas Taleb',
    rating: 4.0,
    genres: ['Philosophy', 'Economics'],
    pages: 544,
    price: 19.99,
    publishYear: 2012,
  },
  {
    id: 94,
    title: 'The Mom Test',
    author: 'Rob Fitzpatrick',
    rating: 4.5,
    genres: ['Business', 'Entrepreneurship'],
    pages: 140,
    price: 14.99,
    publishYear: 2013,
  },
  {
    id: 95,
    title: 'Hooked: How to Build Habit-Forming Products',
    author: 'Nir Eyal',
    rating: 4.1,
    genres: ['Technology', 'Product Design'],
    pages: 256,
    price: 17.99,
    publishYear: 2014,
  },
  {
    id: 96,
    title: 'The Hard Thing About Hard Things',
    author: 'Ben Horowitz',
    rating: 4.3,
    genres: ['Business', 'Entrepreneurship'],
    pages: 304,
    price: 26.99,
    publishYear: 2014,
  },
  {
    id: 97,
    title: 'Educated',
    author: 'Tara Westover',
    rating: 4.4,
    genres: ['Biography', 'Education'],
    pages: 334,
    price: 16.99,
    publishYear: 2018,
  },
  {
    id: 98,
    title: 'The Compound Effect',
    author: 'Darren Hardy',
    rating: 4.1,
    genres: ['Personal Development', 'Success'],
    pages: 162,
    price: 15.99,
    publishYear: 2010,
  },
  {
    id: 99,
    title: 'Radical Candor',
    author: 'Kim Scott',
    rating: 4.2,
    genres: ['Leadership', 'Management'],
    pages: 304,
    price: 19.99,
    publishYear: 2017,
  },
  {
    id: 100,
    title: 'The Culture Code',
    author: 'Daniel Coyle',
    rating: 4.3,
    genres: ['Business', 'Organizational Culture'],
    pages: 304,
    price: 18.99,
    publishYear: 2018,
  },
];

// Utility function to get unique genres
export const getAllGenres = () => {
  const genreSet = new Set();
  bookData.forEach((book) => {
    book.genres.forEach((genre) => genreSet.add(genre));
  });
  return Array.from(genreSet).toSorted();
};

// Utility function to filter books by genre
export const filterBooksByGenre = (books, selectedGenres) => {
  if (selectedGenres.length === 0) return books;
  return books.filter((book) =>
    book.genres.some((genre) => selectedGenres.includes(genre))
  );
};
